trigger:
  branches:
    include:
      - main

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-18.04
  - name: service_connection
    value: GA

stages:
  - stage: Delete_Users
    pool:
      vmImage: ${{ variables.agentPool }}
    jobs:
      - job: Delete_Users
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: ${{ variables.service_connection }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: '$(System.DefaultWorkingDirectory)/pipeline-scripts/delete-users.sh'
