trigger:
  branches:
    include:
      - main

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-18.04
  - name: service_connection
    value: GA

stages:
  - stage: DeleteGuestUsers
    pool:
      vmImage: ${{ variables.agentPool }}
    jobs:
      - job: DeleteUnacceptedInvites
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: ${{ variables.service_connection }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "$(System.DefaultWorkingDirectory)/pipeline-scripts/delete-old-guest-invites.sh"
      - job: DeleteInactiveGuestUsers
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: ${{ variables.service_connection }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "$(System.DefaultWorkingDirectory)/pipeline-scripts/delete-inactive-guest-users.sh"
