name: guest-user-management

schedules:
  - cron: "0 2 * * *"
    displayName: Daily build @ 2am
    always: true
    branches:
      include:
        - master

trigger:
  branches:
    include:
      - master

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - name: service_connection
    value: GA
  - name: apiKeyVault
    value: dtssharedservicesprodkv
  - name: apiKeyName
    value: guest-user-mgmt-notify-api-key

stages:
  - stage: DeleteInactiveGuestUsers
    pool:
      vmImage: ${{ variables.agentPool }}
    jobs:
      - job: DeleteGuestUsers
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - checkout: self

          - task: AzureKeyVault@1
            displayName: Retrieve keyvault secret for API Key
            inputs:
              ConnectedServiceName: ${{ variables.service_connection }}
              keyVaultName: ${{ parameters.keyvaultName }}
              secretsFilter: ${{ parameters.keyvaultSecret }}
              runAsPreJob: false

          - task: AzureCLI@2
            displayName: DeleteUnacceptedInvites
            inputs:
              azureSubscription: ${{ variables.service_connection }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "$(System.DefaultWorkingDirectory)/pipeline-scripts/delete-old-guest-invites.sh"
              arguments: $(Build.SourceBranchName)
          - task: AzureCLI@2
            displayName: DeleteInactiveGuestUsers
            inputs:
              azureSubscription: ${{ variables.service_connection }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "$(System.DefaultWorkingDirectory)/pipeline-scripts/delete-inactive-guest-users.sh"
              arguments: $(Build.SourceBranchName) $(guest-user-mgmt-notify-api-key)

