name: guest-user-management

schedules:
  - cron: "0 6 * * *"
    displayName: Daily build @ 6am
    always: true
    branches:
      include:
        - master

trigger:
  branches:
    include:
      - master

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - name: service_connection
    value: GA

stages:
  - stage: DeleteInactiveGuestUsers
    pool:
      vmImage: ${{ variables.agentPool }}
    jobs:
      - job: DeleteGuestUsers
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: DeleteUnacceptedInvites
            inputs:
              azureSubscription: ${{ variables.service_connection }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "$(System.DefaultWorkingDirectory)/pipeline-scripts/delete-old-guest-invites.sh"
              arguments: $(Build.SourceBranchName)
          - task: AzureCLI@2
            displayName: DeleteInactiveGuestUsers
            inputs:
              azureSubscription: ${{ variables.service_connection }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "$(System.DefaultWorkingDirectory)/pipeline-scripts/delete-inactive-guest-users.sh"
              arguments: $(Build.SourceBranchName)
